services:
  mssql:
    container_name: mysqlserver
    image: mcr.microsoft.com/mssql/server:2019-latest
    user: root
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_PID=Express
      - MSSQL_SA_PASSWORD=MyCoolP@ss2
    ports:
      - 1433:1433
    volumes:
      - ./data/mssql:/var/opt/mssql/data
    networks:
      - test_network

networks:
  test_network:
    driver: bridge
